import "./globals.css";
// import { Inter } from "next/font/google";
import Provider from "./provider";
import { AuthProvider } from "./providerAuth";

// const inter = Inter({ subsets: ["latin"] });
// className={inter.className}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Provider>{children}</Provider>
        </AuthProvider>
      </body>
    </html>
  );
}
